### ISSUE TITLE
Roadmap to 0.2.0

### ISSUE THREAD

**Issue by Shepardeon** [Shepardeon/lvEditor#1]
## Editor
- [x] User is able to create new project
- [x] User is able to open existing project
- [x] User is able to run project through Löve2D
- [ ] Log system is implemented

## Template lib
- [x] Class system is implemented
- [x] Input system is implemented
- [x] Event system is implemented
- [ ] Entity system is implemented
- [ ] Animated sprite system is implemented
- [x] Camera system is implemented
- [ ] Map system is implemented

## Documentation
- [ ] Create the Wiki
- [ ] Document class system
- [ ] Document input system
- [ ] Document event system
- [ ] Document entity system
- [ ] Doculent animated sprite system
- [ ] Document camera system
- [ ] Document map system
